LABEL_TO_DESCRIPTION = {
    "special_hole_tree": "{color} tree with a hollow trunk",
    "triangular_tree": "{color} pine",
    "cluster_club_tree": "cluster of {color} firs",
    "cluster_rounded_tree": "dense cluster of {color} bushes",
    "rounded_tree": "{color} oak tree",
    "club_tree": "{color} fir",
    "grouped_tree_comb1": "pair of two trees—one orange fir and one red hollow-trunk tree",
    "dense_tree": "{color} maple with dense branches",
    "compact_tree": "{color} lantern tree",
    "cluster_compact_tree": "cluster of {color} lantern trees",
    "tiered_tree": "{color} spruce tree with layered branches",
    "chestnut_tree": "{color} chestnut tree",
    "cluster_chestnut_tree": "small grove of {color} chestnut trees",
    "cluster_triangular_tree": "group of {color} pines",
    "grouped_tree_comb2": "cluster of a {color} conical tree and four round trees",
    "grouped_tree_comb3": "group of four orange conical trees with smaller red trees among them",
    "grouped_tree_comb4": "cluster of two rounded {color} bushy trees alongside a cone-shaped tree",
    "snow1": "",
    "snow2": "",
    "snow3": "",
    "snow4": "",
    "snow5": "",
    "iceblock": "",
    'light': 'small roadside decorative lamp with a {color} flame-like glow',
}

WINTER_LABEL_TO_DESCRIPTION = {
    "special_hole_tree": "snow-covered tree with a hollow trunk",
    "triangular_tree": "pine covered in snow",
    "cluster_club_tree": "cluster of snow-covered firs",
    "cluster_rounded_tree": "dense cluster of snow-covered bushes",
    "rounded_tree": "snow-laden oak tree",
    "club_tree": "snow-dusted fir",
    "grouped_tree_comb1": "pair of two snow-covered trees-one fir and one hollow-trunk tree",
    "dense_tree": "snowy maple with dense branches",
    "compact_tree": "snow-covered lantern tree",
    "cluster_compact_tree": "cluster of snow-laden lantern trees",
    "tiered_tree": "snowy spruce tree with layered branches",
    "chestnut_tree": "snow-covered chestnut tree",
    "cluster_chestnut_tree": "small grove of snow-dusted chestnut trees",
    "cluster_triangular_tree": "group of pines covered in snow",
    "grouped_tree_comb2": "cluster of a snow-covered conical tree and four snow-dusted round trees",
    "grouped_tree_comb3": "group of four conical trees with smaller snowy trees among them",
    "grouped_tree_comb4": "cluster of two rounded bushy trees alongside a cone-shaped tree covered in snow",
    "snow1": "pair of cheerful snowmen wearing black hats, surrounded by snowballs",
    "snow2": "smiling snowman with a carrot nose and coal buttons",
    "snow3": "plain snowman without any decorations",
    "snow4": "classic snowman with a hat, carrot nose, and buttons",
    "snow5": "playful snowman duo—one with a hat, one without—surrounded by scattered snowballs",
    "iceblock": "pile of translucent blue ice blocks shimmering in the cold",
    'light': 'small roadside decorative lamp with a {color} flame-like glow',
}

SPECIAL_OBJECTS = [
                   "special_hole_tree", 
                   "grouped_tree_comb1",
                   "grouped_tree_comb2",
                   "grouped_tree_comb3",
                   "grouped_tree_comb4",
                   "cluster_club_tree",
                   "cluster_rounded_tree",
                   "cluster_compact_tree",
                   "cluster_chestnut_tree",
                   "cluster_triangular_tree",
                   ]

WINTER_SPECIAL_OBJECTS = [  "snow1", 
                            "snow2",
                            "snow3",
                            "snow4",
                            "snow5",
                            "iceblock",
                            ]

ADDITIONAL_LABELS = {
    'barricade': 'wooden barricade with red and white stripes, marking a road construction area',
    'cone': 'pointed construction cone with bold red and white stripes',
}